pipeline:
  create_cluster:
    image: banzaicloud/ci-pipeline-client:0.10.1
    cluster:
      name: waynz0r2gb2
      location: ""
      cloud: amazon
      secretId: ""
      secretName: ""
      profileName: ""
      postHooks: {}
      properties: null
    action: EnsureCluster
  test:
    image: node:10-slim
    commands:
    - npm ci
    - npm test
  build_image:
    dockerfile: Dockerfile
    image: plugins/docker
    repo: '{{ .CICD_REPO }}'
    secretFrom:
      DOCKER_PASSWORD:
        keyRef: password
        name: docker-hub
      DOCKER_USERNAME:
        keyRef: username
        name: docker-hub
    tags: '{{ trunc 7 .CICD_COMMIT_SHA }}'
  package_application:
    when:
      branch:
        include:
        - master
    image: lachlanevenson/k8s-helm:latest
    commands:
    - helm init -c
    - helm repo add banzaicloud-stable http://kubernetes-charts.banzaicloud.com/branch/master
    - helm package ./.banzaicloud/charts/spotguide-nodejs-mongodb
  install_mongodb_user_secret:
    action: InstallSecret
    clusterSecret:
      merge: true
      name: '{{ .CICD_REPO_NAME }}-mongodb'
      namespace: default
      sourceSecretName: nodejs-mongodb-mongodb
      spec:
      - name: mongodb-username
        source: username
      - name: mongodb-password
        source: password
    image: banzaicloud/ci-pipeline-client:0.10.1
    when:
      branch:
        include:
        - master
  install_mongodb_root_secret:
    when:
      branch:
        include:
        - master
    image: banzaicloud/ci-pipeline-client:0.10.1
    action: InstallSecret
    clusterSecret:
      name: '{{ .CICD_REPO_NAME }}-mongodb'
      namespace: default
      merge: true
      spec:
      - name: mongodb-root-password
        source: password
  install_mongodb_replica_set_key_secret:
    action: InstallSecret
    clusterSecret:
      merge: true
      name: '{{ .CICD_REPO_NAME }}-mongodb'
      namespace: default
      sourceSecretName: nodejs-mongodb-mongodb-replicaset-key
      spec:
      - name: mongodb-replica-set-key
        source: password
    image: banzaicloud/ci-pipeline-client:0.10.1
    when:
      branch:
        include:
        - master
  deploy_application:
    action: EnsureDeployment
    deployment:
      Values:
        deployment:
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 128Mi
      name: ./spotguide-nodejs-mongodb-1.0.0.tgz
      releaseName: '{{ .CICD_REPO_NAME }}'
      reuseValues: true
      timeout: 900
      values:
        deployment:
          image:
            pullPolicy: Always
            repository: '{{ .CICD_REPO }}'
            tag: '{{ trunc 7 .CICD_COMMIT_SHA }}'
        ingress:
          annotations:
            kubernetes.io/ingress.class: traefik
            traefik.ingress.kubernetes.io/redirect-permanent: "true"
            traefik.ingress.kubernetes.io/redirect-regex: ^http://(.*)
            traefik.ingress.kubernetes.io/redirect-replacement: https://$1
          hosts:
          - app-{{.CICD_REPO_NAME}}.{{.CLUSTER_NAME}}.{{.ORG_NAME}}.{{.DOMAIN_NAME}}
        mongodb:
          existingSecret: '{{ .CICD_REPO_NAME }}-mongodb'
          metrics:
            enabled: true
          mongodbDatabase: node-application
          replicaSet:
            enabled: true
          usePassword: true
      wait: true
    image: banzaicloud/ci-pipeline-client:0.10.1
    when:
      branch:
        include:
        - master
